version: '3.8'

services:
  pdf-service:
    build: .
    container_name: pdf_service_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    command: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --backlog 2048 --keep-alive 5
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
